image: gcc

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - apt update && apt -y install cmake
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - cd ..
    - cmake --build build
  artifacts:
    paths:
      - build
  cache:
    paths:
      - build

test:
  stage: test
  dependencies:
    - build
  script:
    - ./build/run_tests
